/* The following code was generated by JFlex 1.6.1 */

import java_cup.runtime.*;
//...

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>src/Lexer.lex</tt>
 */
class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\2\2\0\1\1\22\0\1\3\1\11\1\7\1\12"+
    "\1\0\1\13\1\14\1\6\1\15\1\16\1\17\1\20\1\21\1\22"+
    "\1\23\1\24\12\5\1\25\1\26\1\27\1\30\1\31\1\13\1\13"+
    "\5\4\1\37\15\4\1\37\6\4\1\32\1\13\1\33\1\13\1\10"+
    "\1\13\1\47\1\40\1\51\1\57\1\56\1\50\1\55\1\52\1\43"+
    "\2\4\1\42\1\64\1\44\1\41\1\53\1\60\1\46\1\54\1\45"+
    "\1\62\1\63\1\61\3\4\1\34\1\36\1\35\1\13\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uff91\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\3\2\1\3\1\4\4\1\1\5\1\1"+
    "\1\6\1\7\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\1\24\1\25"+
    "\1\26\1\1\1\27\20\3\1\0\2\30\3\0\1\30"+
    "\4\0\1\5\1\0\1\31\1\5\1\32\1\33\1\5"+
    "\1\34\1\35\4\0\1\36\1\0\1\37\1\3\1\40"+
    "\1\3\1\41\1\42\10\3\1\43\6\3\1\44\4\3"+
    "\3\0\1\5\1\0\1\45\1\46\1\47\2\0\1\5"+
    "\4\0\1\5\1\3\1\50\1\51\13\3\1\52\6\3"+
    "\1\0\2\30\7\0\1\53\1\54\1\3\1\55\2\3"+
    "\1\56\2\3\1\57\1\60\1\61\1\3\1\62\1\63"+
    "\1\5\3\0\1\5\1\3\1\64\1\3\1\65\1\3"+
    "\1\66\2\0\1\67\1\70";

  private static int [] zzUnpackAction() {
    int [] result = new int[177];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\65\0\152\0\65\0\237\0\324\0\u0109\0\u013e"+
    "\0\u0173\0\u01a8\0\u01dd\0\u01a8\0\u0212\0\u01a8\0\u01a8\0\u01a8"+
    "\0\u01a8\0\u01a8\0\u0247\0\u01a8\0\u027c\0\u02b1\0\u01a8\0\u01a8"+
    "\0\u02e6\0\u01a8\0\u01a8\0\u01a8\0\u031b\0\u01a8\0\u0350\0\324"+
    "\0\u0385\0\u03ba\0\u03ef\0\u0424\0\u0459\0\u048e\0\u04c3\0\u04f8"+
    "\0\u052d\0\u0562\0\u0597\0\u05cc\0\u0601\0\u0636\0\u066b\0\u06a0"+
    "\0\237\0\u06d5\0\u070a\0\u073f\0\u01a8\0\u0774\0\u07a9\0\u07de"+
    "\0\u0813\0\u0848\0\u087d\0\u087d\0\u0173\0\u0173\0\u0173\0\u01a8"+
    "\0\u01a8\0\u08b2\0\u01a8\0\u01a8\0\u08e7\0\u091c\0\u0951\0\u0986"+
    "\0\u01a8\0\u09bb\0\u01a8\0\u09f0\0\324\0\u0a25\0\u0a5a\0\324"+
    "\0\u0a8f\0\u0ac4\0\u0af9\0\u0a5a\0\u0b2e\0\u0b63\0\u0b98\0\u0bcd"+
    "\0\324\0\u0c02\0\u0c37\0\u0c6c\0\u0ca1\0\u0cd6\0\u0d0b\0\324"+
    "\0\u0d40\0\u0d75\0\u0daa\0\u0ddf\0\u0e14\0\u0e49\0\u0e7e\0\u0e7e"+
    "\0\u0eb3\0\u0ee8\0\u0f1d\0\u0f52\0\u08b2\0\u0f87\0\u0fbc\0\u0ff1"+
    "\0\u1026\0\u105b\0\u1090\0\u1090\0\u10c5\0\324\0\324\0\u10fa"+
    "\0\u112f\0\u1164\0\u1199\0\u11ce\0\u1203\0\u1238\0\u126d\0\u12a2"+
    "\0\u12d7\0\u130c\0\324\0\u1341\0\u1376\0\u13ab\0\u13e0\0\u1415"+
    "\0\u144a\0\u147f\0\u14b4\0\u0f52\0\u14e9\0\u151e\0\u1553\0\u1588"+
    "\0\u15bd\0\u15f2\0\u1627\0\324\0\324\0\u165c\0\324\0\u1691"+
    "\0\u16c6\0\324\0\u16fb\0\u1730\0\324\0\324\0\324\0\u1765"+
    "\0\324\0\324\0\u0f87\0\u179a\0\u17cf\0\u1804\0\u1804\0\u1839"+
    "\0\324\0\u186e\0\324\0\u18a3\0\324\0\u18d8\0\u190d\0\324"+
    "\0\324";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[177];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\12\1\15\1\16\1\17\1\20"+
    "\1\21\1\22\1\23\1\24\1\25\1\26\1\27\1\30"+
    "\1\31\1\32\1\33\1\34\1\35\1\36\1\37\1\40"+
    "\1\41\1\42\1\43\1\44\1\6\1\45\1\46\1\47"+
    "\1\50\1\51\1\6\1\52\1\53\1\6\1\54\1\55"+
    "\1\6\1\56\1\6\1\57\1\60\66\0\1\61\1\4"+
    "\1\61\1\62\1\63\1\64\3\65\1\14\7\65\1\66"+
    "\14\65\26\62\1\0\1\61\1\0\1\61\1\62\1\63"+
    "\1\64\3\65\1\14\7\65\1\66\14\65\26\62\1\0"+
    "\1\67\1\0\1\67\2\6\2\65\1\6\1\65\1\14"+
    "\6\65\1\61\15\65\26\6\1\0\1\67\1\0\1\67"+
    "\1\65\1\7\2\65\1\70\1\65\1\14\6\65\1\61"+
    "\1\65\1\71\1\72\40\65\1\0\1\65\1\0\1\65"+
    "\6\73\1\74\52\73\1\0\1\75\1\0\4\75\1\76"+
    "\2\75\1\77\52\75\1\0\1\65\1\0\7\65\1\14"+
    "\52\65\1\0\1\65\1\0\7\65\1\14\15\65\1\100"+
    "\34\65\1\0\1\65\1\0\7\65\1\14\1\65\1\101"+
    "\50\65\1\0\1\65\1\0\2\65\1\7\4\65\1\14"+
    "\52\65\1\0\1\65\1\0\7\65\1\102\52\65\1\0"+
    "\1\65\1\0\7\65\1\14\12\65\1\103\37\65\1\0"+
    "\1\65\1\0\7\65\1\14\15\65\1\104\34\65\1\0"+
    "\1\105\1\0\1\105\1\65\1\106\1\107\3\65\1\14"+
    "\7\65\1\110\12\65\1\111\1\65\1\112\25\65\1\0"+
    "\1\65\1\0\7\65\1\14\23\65\1\113\26\65\1\0"+
    "\1\67\1\0\1\67\2\6\2\65\1\6\1\65\1\14"+
    "\6\65\1\61\15\65\2\6\1\114\23\6\1\0\1\67"+
    "\1\0\1\67\2\6\2\65\1\6\1\65\1\14\6\65"+
    "\1\61\15\65\20\6\1\115\5\6\1\0\1\67\1\0"+
    "\1\67\2\6\2\65\1\6\1\65\1\14\6\65\1\61"+
    "\15\65\17\6\1\116\6\6\1\0\1\67\1\0\1\67"+
    "\2\6\2\65\1\6\1\65\1\14\6\65\1\61\15\65"+
    "\5\6\1\117\3\6\1\120\14\6\1\0\1\67\1\0"+
    "\1\67\2\6\2\65\1\6\1\65\1\14\6\65\1\61"+
    "\15\65\2\6\1\121\10\6\1\122\4\6\1\123\5\6"+
    "\1\0\1\67\1\0\1\67\2\6\2\65\1\6\1\65"+
    "\1\14\6\65\1\61\15\65\10\6\1\124\6\6\1\125"+
    "\6\6\1\0\1\67\1\0\1\67\2\6\2\65\1\6"+
    "\1\65\1\14\6\65\1\61\15\65\3\6\1\126\22\6"+
    "\1\0\1\67\1\0\1\67\2\6\2\65\1\6\1\65"+
    "\1\14\6\65\1\61\15\65\2\6\1\127\1\130\1\131"+
    "\13\6\1\132\5\6\1\0\1\67\1\0\1\67\2\6"+
    "\2\65\1\6\1\65\1\14\6\65\1\61\15\65\13\6"+
    "\1\133\12\6\1\0\1\67\1\0\1\67\2\6\2\65"+
    "\1\6\1\65\1\14\6\65\1\61\15\65\7\6\1\134"+
    "\16\6\1\0\1\67\1\0\1\67\2\6\2\65\1\6"+
    "\1\65\1\14\6\65\1\61\15\65\6\6\1\135\10\6"+
    "\1\136\6\6\1\0\1\67\1\0\1\67\2\6\2\65"+
    "\1\6\1\65\1\14\6\65\1\61\15\65\3\6\1\137"+
    "\22\6\1\0\1\67\1\0\1\67\2\6\2\65\1\6"+
    "\1\65\1\14\6\65\1\61\15\65\2\6\1\140\1\6"+
    "\1\141\21\6\1\0\1\67\1\0\1\67\2\6\2\65"+
    "\1\6\1\65\1\14\6\65\1\61\15\65\13\6\1\142"+
    "\12\6\1\0\1\67\1\0\1\67\2\6\2\65\1\6"+
    "\1\65\1\14\6\65\1\61\15\65\2\6\1\143\23\6"+
    "\1\0\1\67\1\0\1\67\2\6\2\65\1\6\1\65"+
    "\1\14\6\65\1\61\15\65\10\6\1\144\15\6\1\0"+
    "\1\67\1\0\1\67\2\62\2\65\1\62\1\65\1\14"+
    "\6\65\1\61\15\65\26\62\1\0\1\67\1\0\1\67"+
    "\1\65\1\63\2\65\1\145\1\65\1\14\6\65\1\61"+
    "\1\65\2\146\40\65\1\0\1\65\1\0\1\65\6\147"+
    "\1\150\52\147\1\0\1\65\1\0\2\65\1\63\4\65"+
    "\1\14\52\65\1\0\1\67\1\0\1\67\6\65\1\14"+
    "\52\65\1\0\1\65\1\0\2\65\1\151\4\65\1\14"+
    "\52\65\1\0\1\65\1\0\2\65\1\152\4\65\1\14"+
    "\52\65\1\0\1\65\1\0\2\65\1\153\4\65\1\14"+
    "\52\65\1\0\1\65\1\0\3\65\1\154\3\65\1\14"+
    "\52\65\1\0\1\155\1\156\7\155\1\157\52\155\1\0"+
    "\1\105\1\0\1\105\1\65\1\106\1\107\3\65\1\14"+
    "\7\65\1\110\14\65\1\112\25\65\1\0\1\112\1\0"+
    "\1\112\1\65\1\106\2\65\1\160\1\65\1\14\10\65"+
    "\2\161\1\162\37\65\1\0\1\65\1\0\1\65\6\163"+
    "\1\164\52\163\1\0\1\65\1\0\2\65\1\106\4\65"+
    "\1\14\52\65\1\0\1\112\1\0\1\112\6\65\1\14"+
    "\12\65\1\162\37\65\1\0\1\67\1\0\1\67\2\6"+
    "\2\65\1\6\1\65\1\14\6\65\1\61\15\65\2\6"+
    "\1\165\23\6\1\0\1\67\1\0\1\67\2\6\2\65"+
    "\1\6\1\65\1\14\6\65\1\61\15\65\6\6\1\166"+
    "\17\6\1\0\1\67\1\0\1\67\2\6\2\65\1\6"+
    "\1\65\1\14\6\65\1\61\15\65\6\6\1\167\17\6"+
    "\1\0\1\67\1\0\1\67\2\6\2\65\1\6\1\65"+
    "\1\14\6\65\1\61\15\65\14\6\1\167\11\6\1\0"+
    "\1\67\1\0\1\67\2\6\2\65\1\6\1\65\1\14"+
    "\6\65\1\61\15\65\17\6\1\170\6\6\1\0\1\67"+
    "\1\0\1\67\2\6\2\65\1\6\1\65\1\14\6\65"+
    "\1\61\15\65\17\6\1\171\6\6\1\0\1\67\1\0"+
    "\1\67\2\6\2\65\1\6\1\65\1\14\6\65\1\61"+
    "\15\65\6\6\1\172\1\6\1\173\15\6\1\0\1\67"+
    "\1\0\1\67\2\6\2\65\1\6\1\65\1\14\6\65"+
    "\1\61\15\65\4\6\1\174\21\6\1\0\1\67\1\0"+
    "\1\67\2\6\2\65\1\6\1\65\1\14\6\65\1\61"+
    "\15\65\7\6\1\175\16\6\1\0\1\67\1\0\1\67"+
    "\2\6\2\65\1\6\1\65\1\14\6\65\1\61\15\65"+
    "\2\6\1\176\23\6\1\0\1\67\1\0\1\67\2\6"+
    "\2\65\1\6\1\65\1\14\6\65\1\61\15\65\17\6"+
    "\1\177\6\6\1\0\1\67\1\0\1\67\2\6\2\65"+
    "\1\6\1\65\1\14\6\65\1\61\15\65\10\6\1\200"+
    "\15\6\1\0\1\67\1\0\1\67\2\6\2\65\1\6"+
    "\1\65\1\14\6\65\1\61\15\65\4\6\1\201\21\6"+
    "\1\0\1\67\1\0\1\67\2\6\2\65\1\6\1\65"+
    "\1\14\6\65\1\61\15\65\7\6\1\202\16\6\1\0"+
    "\1\67\1\0\1\67\2\6\2\65\1\6\1\65\1\14"+
    "\6\65\1\61\15\65\21\6\1\203\4\6\1\0\1\67"+
    "\1\0\1\67\2\6\2\65\1\6\1\65\1\14\6\65"+
    "\1\61\15\65\4\6\1\204\10\6\1\205\10\6\1\0"+
    "\1\67\1\0\1\67\2\6\2\65\1\6\1\65\1\14"+
    "\6\65\1\61\15\65\12\6\1\206\13\6\1\0\1\67"+
    "\1\0\1\67\2\6\2\65\1\6\1\65\1\14\6\65"+
    "\1\61\15\65\4\6\1\207\21\6\1\0\1\67\1\0"+
    "\1\67\2\6\2\65\1\6\1\65\1\14\6\65\1\61"+
    "\15\65\4\6\1\210\21\6\1\0\1\67\1\0\1\67"+
    "\2\6\2\65\1\6\1\65\1\14\6\65\1\61\15\65"+
    "\4\6\1\211\21\6\1\0\1\65\1\0\2\65\1\212"+
    "\4\65\1\14\52\65\1\0\1\65\1\0\2\65\1\213"+
    "\4\65\1\14\52\65\1\0\1\65\1\0\3\65\1\214"+
    "\3\65\1\14\52\65\1\0\1\65\1\0\2\65\1\151"+
    "\4\65\1\14\11\65\1\72\40\65\1\0\1\67\1\0"+
    "\1\67\1\65\1\152\4\65\1\14\6\65\1\61\43\65"+
    "\1\0\1\67\1\0\1\67\1\65\1\153\4\65\1\14"+
    "\6\65\1\61\43\65\1\0\1\67\1\0\1\67\6\65"+
    "\1\14\6\65\1\61\43\65\1\0\11\156\1\215\52\156"+
    "\1\0\1\155\1\156\7\155\1\157\11\155\1\102\40\155"+
    "\1\0\1\65\1\0\2\65\1\216\4\65\1\14\52\65"+
    "\1\0\1\65\1\0\2\65\1\217\4\65\1\14\52\65"+
    "\1\0\1\162\1\0\1\162\1\65\1\220\1\221\3\65"+
    "\1\14\7\65\1\222\14\65\1\223\25\65\1\0\1\65"+
    "\1\0\3\65\1\112\3\65\1\14\52\65\1\0\1\67"+
    "\1\0\1\67\2\6\2\65\1\6\1\65\1\14\6\65"+
    "\1\61\15\65\3\6\1\167\22\6\1\0\1\67\1\0"+
    "\1\67\2\6\2\65\1\6\1\65\1\14\6\65\1\61"+
    "\15\65\5\6\1\224\20\6\1\0\1\67\1\0\1\67"+
    "\2\6\2\65\1\6\1\65\1\14\6\65\1\61\15\65"+
    "\11\6\1\225\14\6\1\0\1\67\1\0\1\67\2\6"+
    "\2\65\1\6\1\65\1\14\6\65\1\61\15\65\23\6"+
    "\1\226\2\6\1\0\1\67\1\0\1\67\2\6\2\65"+
    "\1\6\1\65\1\14\6\65\1\61\15\65\20\6\1\227"+
    "\5\6\1\0\1\67\1\0\1\67\2\6\2\65\1\6"+
    "\1\65\1\14\6\65\1\61\15\65\10\6\1\230\15\6"+
    "\1\0\1\67\1\0\1\67\2\6\2\65\1\6\1\65"+
    "\1\14\6\65\1\61\15\65\10\6\1\231\15\6\1\0"+
    "\1\67\1\0\1\67\2\6\2\65\1\6\1\65\1\14"+
    "\6\65\1\61\15\65\10\6\1\124\15\6\1\0\1\67"+
    "\1\0\1\67\2\6\2\65\1\6\1\65\1\14\6\65"+
    "\1\61\15\65\11\6\1\232\14\6\1\0\1\67\1\0"+
    "\1\67\2\6\2\65\1\6\1\65\1\14\6\65\1\61"+
    "\15\65\7\6\1\167\16\6\1\0\1\67\1\0\1\67"+
    "\2\6\2\65\1\6\1\65\1\14\6\65\1\61\15\65"+
    "\5\6\1\233\20\6\1\0\1\67\1\0\1\67\2\6"+
    "\2\65\1\6\1\65\1\14\6\65\1\61\15\65\4\6"+
    "\1\234\21\6\1\0\1\67\1\0\1\67\2\6\2\65"+
    "\1\6\1\65\1\14\6\65\1\61\15\65\11\6\1\235"+
    "\14\6\1\0\1\67\1\0\1\67\2\6\2\65\1\6"+
    "\1\65\1\14\6\65\1\61\15\65\17\6\1\236\6\6"+
    "\1\0\1\67\1\0\1\67\2\6\2\65\1\6\1\65"+
    "\1\14\6\65\1\61\15\65\6\6\1\237\17\6\1\0"+
    "\1\67\1\0\1\67\2\6\2\65\1\6\1\65\1\14"+
    "\6\65\1\61\15\65\3\6\1\240\22\6\1\0\1\67"+
    "\1\0\1\67\2\6\2\65\1\6\1\65\1\14\6\65"+
    "\1\61\15\65\20\6\1\241\5\6\1\0\1\67\1\0"+
    "\1\67\2\6\2\65\1\6\1\65\1\14\6\65\1\61"+
    "\15\65\5\6\1\242\20\6\1\0\1\65\1\0\2\65"+
    "\1\212\4\65\1\14\11\65\1\146\40\65\1\0\1\67"+
    "\1\0\1\67\1\65\1\213\4\65\1\14\6\65\1\61"+
    "\43\65\1\0\11\156\1\215\11\156\1\243\40\156\1\0"+
    "\1\65\1\0\2\65\1\216\4\65\1\14\11\65\1\161"+
    "\40\65\1\0\1\112\1\0\1\112\1\65\1\217\4\65"+
    "\1\14\12\65\1\162\37\65\1\0\1\223\1\0\1\223"+
    "\1\65\1\220\2\65\1\244\1\65\1\14\6\65\1\105"+
    "\1\65\2\245\10\65\1\111\27\65\1\0\1\65\1\0"+
    "\1\65\6\246\1\247\52\246\1\0\1\65\1\0\2\65"+
    "\1\220\4\65\1\14\52\65\1\0\1\223\1\0\1\223"+
    "\6\65\1\14\6\65\1\105\13\65\1\111\27\65\1\0"+
    "\1\67\1\0\1\67\2\6\2\65\1\6\1\65\1\14"+
    "\6\65\1\61\15\65\7\6\1\250\16\6\1\0\1\67"+
    "\1\0\1\67\2\6\2\65\1\6\1\65\1\14\6\65"+
    "\1\61\15\65\15\6\1\251\10\6\1\0\1\67\1\0"+
    "\1\67\2\6\2\65\1\6\1\65\1\14\6\65\1\61"+
    "\15\65\3\6\1\252\22\6\1\0\1\67\1\0\1\67"+
    "\2\6\2\65\1\6\1\65\1\14\6\65\1\61\15\65"+
    "\6\6\1\253\17\6\1\0\1\67\1\0\1\67\2\6"+
    "\2\65\1\6\1\65\1\14\6\65\1\61\15\65\5\6"+
    "\1\254\20\6\1\0\1\67\1\0\1\67\2\6\2\65"+
    "\1\6\1\65\1\14\6\65\1\61\15\65\17\6\1\255"+
    "\6\6\1\0\1\65\1\0\2\65\1\256\4\65\1\14"+
    "\52\65\1\0\1\65\1\0\2\65\1\257\4\65\1\14"+
    "\52\65\1\0\1\65\1\0\3\65\1\223\3\65\1\14"+
    "\52\65\1\0\1\67\1\0\1\67\2\6\2\65\1\6"+
    "\1\65\1\14\6\65\1\61\15\65\5\6\1\260\20\6"+
    "\1\0\1\67\1\0\1\67\2\6\2\65\1\6\1\65"+
    "\1\14\6\65\1\61\15\65\3\6\1\261\22\6\1\0"+
    "\1\67\1\0\1\67\2\6\2\65\1\6\1\65\1\14"+
    "\6\65\1\61\15\65\16\6\1\167\7\6\1\0\1\65"+
    "\1\0\2\65\1\256\4\65\1\14\11\65\1\245\40\65"+
    "\1\0\1\223\1\0\1\223\1\65\1\257\4\65\1\14"+
    "\6\65\1\105\13\65\1\111\27\65";

  private static int [] zzUnpackTrans() {
    int [] result = new int[6466];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\1\1\1\11\54\1\1\0\2\1\3\0"+
    "\1\1\4\0\1\1\1\0\7\1\4\0\1\1\1\0"+
    "\32\1\3\0\1\1\1\0\3\1\2\0\1\1\4\0"+
    "\26\1\1\0\2\1\7\0\20\1\3\0\7\1\2\0"+
    "\2\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[177];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
  private boolean debug_mode;
  public  boolean debug()            { return debug_mode; }
  public  void    debug(boolean mode){ debug_mode = mode; }

  private void print_lexeme(int type, Object value){
    if(!debug()){ return; }

    System.out.print("<");
    switch(type){
      case sym.LET:
        System.out.print("LET"); break;
      case sym.EQUAL:
        System.out.print("="); break;
      case sym.SEMICOL:
        System.out.print(";"); break;
      case sym.PLUS:
        System.out.print("+"); break;
      case sym.MINUS:
        System.out.print("-"); break;
      case sym.MULT:
        System.out.print("*"); break;
      case sym.DIV:
        System.out.print("/"); break;
      case sym.LPAREN:
        System.out.print("("); break;
      case sym.RPAREN:
        System.out.print(")"); break;
      case sym.SLPAREN:
        System.out.print("["); break;
      case sym.SRPAREN:
        System.out.print("]"); break;
      case sym.CLPAREN:
        System.out.print("{"); break;
      case sym.CRPAREN:
        System.out.print("}"); break;
      case sym.PLPAREN:
        System.out.print("<"); break;
      case sym.PRPAREN:
        System.out.print(">"); break;
      case sym.COLON:
        System.out.print(":"); break;
      case sym.COMMA:
        System.out.print(","); break;
      case sym.DOT:
        System.out.print("."); break;
      case sym.DOTDOT:
        System.out.print("::"); break;
      case sym.EQEQ:
        System.out.print("=="); break;
      case sym.NOTEQ:
        System.out.print("!="); break;
      case sym.ANDAND:
        System.out.print("&&"); break;
      case sym.OROR:
        System.out.print("||"); break;
      case sym.DICTD:
        System.out.print("dict"); break;
      case sym.SEQD:
        System.out.print("seq"); break; 
      case sym.TDEF:
        System.out.print("tdef"); break;
      case sym.FDEF:
        System.out.print("fdef"); break;
      case sym.ALIAS:
        System.out.print("alias"); break;
      case sym.READ:
        System.out.print("read"); break;
      case sym.PRINT:
        System.out.print("print"); break;
      case sym.IF:
        System.out.print("if"); break;
      case sym.THEN:
        System.out.print("then"); break;
      case sym.FI:
        System.out.print("fi"); break;
      case sym.ELSE:
        System.out.print("else"); break;
      case sym.ELIF:
        System.out.print("elif"); break;
      case sym.WHILE:
        System.out.print("while"); break;
      case sym.DO:
        System.out.print("do"); break;
      case sym.OD:
        System.out.print("od"); break;
      case sym.FORALL:
        System.out.print("forall"); break;
      case sym.IN:
        System.out.print("in"); break;
      case sym.RETURN:
        System.out.print("return"); break;
      case sym.VOID:
        System.out.print("void"); break;
      case sym.MAIN:
        System.out.print("main"); break;
      case sym.INT:
        System.out.printf("INT %d", value); break;
      case sym.FLOAT:
        System.out.printf("FLOAT %f", value); break;
      case sym.RAT:
        System.out.printf("RAT %s", value); break;
      case sym.CHAR:
        System.out.printf("CHAR %s", value); break;
      case sym.IDENTIFIER:
        System.out.printf("IDENT %s", value); break;
      case sym.COMMENT:
        System.out.printf("COMMENT %s", value); break;
      case sym.BOOLEAN:
        System.out.printf("BOOL %s", value); break;
      case sym.STR:
        System.out.printf("STR %s", value); break;
      case sym.DICT:
        System.out.printf("DICT %s", value); break;
      case sym.DATATYPE:
        System.out.printf("DATATYPE %s", value); break;
      case sym.SEQ:
        System.out.printf("SEQUENCE %s", value); break;
    }
    System.out.print(">");
  }

  private Symbol symbol(int type) {
    print_lexeme(type, null);
    return new Symbol(type, yyline, yycolumn);
  }
  private Symbol symbol(int type, Object value) {
    print_lexeme(type, value);
    return new Symbol(type, yyline, yycolumn, value);
  }



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 170) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { System.out.println("file:" + (yyline+1) +
    ":0: Error: Invalid input '" + yytext()+"'");
  return symbol(sym.BADCHAR);
            }
          case 57: break;
          case 2: 
            { /* do nothing */
            }
          case 58: break;
          case 3: 
            { return symbol(sym.IDENTIFIER, yytext());
            }
          case 59: break;
          case 4: 
            { return symbol(sym.INT, Integer.parseInt(yytext()));
            }
          case 60: break;
          case 5: 
            { return symbol(sym.COMMENT, yytext());
            }
          case 61: break;
          case 6: 
            { return symbol(sym.LPAREN);
            }
          case 62: break;
          case 7: 
            { return symbol(sym.RPAREN);
            }
          case 63: break;
          case 8: 
            { return symbol(sym.MULT);
            }
          case 64: break;
          case 9: 
            { return symbol(sym.PLUS);
            }
          case 65: break;
          case 10: 
            { return symbol(sym.COMMA);
            }
          case 66: break;
          case 11: 
            { return symbol(sym.MINUS);
            }
          case 67: break;
          case 12: 
            { return symbol(sym.DOT);
            }
          case 68: break;
          case 13: 
            { return symbol(sym.DIV);
            }
          case 69: break;
          case 14: 
            { return symbol(sym.COLON);
            }
          case 70: break;
          case 15: 
            { return symbol(sym.SEMICOL);
            }
          case 71: break;
          case 16: 
            { return symbol(sym.PLPAREN);
            }
          case 72: break;
          case 17: 
            { return symbol(sym.EQUAL);
            }
          case 73: break;
          case 18: 
            { return symbol(sym.PRPAREN);
            }
          case 74: break;
          case 19: 
            { return symbol(sym.SLPAREN);
            }
          case 75: break;
          case 20: 
            { return symbol(sym.SRPAREN);
            }
          case 76: break;
          case 21: 
            { return symbol(sym.CLPAREN);
            }
          case 77: break;
          case 22: 
            { return symbol(sym.CRPAREN);
            }
          case 78: break;
          case 23: 
            { return symbol(sym.BOOLEAN, yytext());
            }
          case 79: break;
          case 24: 
            { return symbol(sym.SEQ, yytext());
            }
          case 80: break;
          case 25: 
            { return symbol(sym.STR, yytext());
            }
          case 81: break;
          case 26: 
            { return symbol(sym.NOTEQ);
            }
          case 82: break;
          case 27: 
            { return symbol(sym.ANDAND);
            }
          case 83: break;
          case 28: 
            { return symbol(sym.DOTDOT);
            }
          case 84: break;
          case 29: 
            { return symbol(sym.EQEQ);
            }
          case 85: break;
          case 30: 
            { return symbol(sym.DICT, yytext());
            }
          case 86: break;
          case 31: 
            { return symbol(sym.OROR);
            }
          case 87: break;
          case 32: 
            { return symbol(sym.OD);
            }
          case 88: break;
          case 33: 
            { return symbol(sym.IN);
            }
          case 89: break;
          case 34: 
            { return symbol(sym.IF);
            }
          case 90: break;
          case 35: 
            { return symbol(sym.FI);
            }
          case 91: break;
          case 36: 
            { return symbol(sym.DO);
            }
          case 92: break;
          case 37: 
            { return symbol(sym.FLOAT, Float.parseFloat(yytext()));
            }
          case 93: break;
          case 38: 
            { return symbol(sym.RAT, yytext());
            }
          case 94: break;
          case 39: 
            { return symbol(sym.CHAR, yytext());
            }
          case 95: break;
          case 40: 
            { return symbol(sym.LET);
            }
          case 96: break;
          case 41: 
            { return symbol(sym.DATATYPE, yytext());
            }
          case 97: break;
          case 42: 
            { return symbol(sym.SEQD);
            }
          case 98: break;
          case 43: 
            { return symbol(sym.THEN);
            }
          case 99: break;
          case 44: 
            { return symbol(sym.TDEF);
            }
          case 100: break;
          case 45: 
            { return symbol(sym.READ);
            }
          case 101: break;
          case 46: 
            { return symbol(sym.FDEF);
            }
          case 102: break;
          case 47: 
            { return symbol(sym.ELIF);
            }
          case 103: break;
          case 48: 
            { return symbol(sym.ELSE);
            }
          case 104: break;
          case 49: 
            { return symbol(sym.DICTD);
            }
          case 105: break;
          case 50: 
            { return symbol(sym.VOID);
            }
          case 106: break;
          case 51: 
            { return symbol(sym.MAIN);
            }
          case 107: break;
          case 52: 
            { return symbol(sym.ALIAS);
            }
          case 108: break;
          case 53: 
            { return symbol(sym.PRINT);
            }
          case 109: break;
          case 54: 
            { return symbol(sym.WHILE);
            }
          case 110: break;
          case 55: 
            { return symbol(sym.RETURN);
            }
          case 111: break;
          case 56: 
            { return symbol(sym.FORALL);
            }
          case 112: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
